In [2]:
import time
import json
import re
import os 
import tensorflow as tf
import pandas as pd
import numpy as np
from itertools import compress
import matplotlib.pyplot as plt


In [2]:
def json_to_csv(directory, fileNames, createSample=False):
    """
    json_to_csv: loops through specified JSON files and converts them to csv files.
                 option to also create a sample csv, which uses np.random.seed 9001 to create a sample dataset with 10% of the observations
    
                 pandas has a read_json function, but returns a 'Trailing data error' when working with these specific files
                 
                 
    Inputs: -directory of JSON files
            -list of JSON filenames
            -createSample flag
            
    """
    
    start = time.time()

    jsonData = []

    for fileName in fileNames:
        with open(directory + fileName,  encoding="utf8") as file:
            print('{0} opened'.format(fileName))
            for line in file:
                #I use an rstrip here because some of the files have trailing blank spaces
                jsonData.append(json.loads(line.rstrip()))
        
        df = pd.DataFrame.from_dict(jsonData)
        
        csvFileName = fileName[:len(fileName)-5] + '.csv'
        
        df.to_csv(directory + csvFileName)
        print('{0} created'.format(csvFileName))
        
        
        if createSample:
            np.random.seed(9001)
            msk = np.random.rand(len(df)) <= 0.1
            sample = df[msk]
            
            csvSampleFileName = fileName[:len(fileName)-5] + '_sample.csv'
            
            sample.to_csv(directory + csvSampleFileName)
            print('{0} created'.format(csvSampleFileName))
        
    print('This function took {} minutes to run'.format((time.time()-start)/60))
    

In [3]:
df_business = pd.read_json('data/business.json', lines=True)

# df_business.dropna(inplace=True, subset = ['categories'], axis=0)

# df_business.loc[df_business['categories'].str.contains('Restaurants')]

# df_business['categories'].value_counts()

In [4]:
df_business.head()

address  \
0     2818 E Camino Acequia Drive   
1            30 Eglinton Avenue W   
2       10110 Johnston Rd, Ste 15   
3   15655 W Roosevelt St, Ste 237   
4  4209 Stuart Andrew Blvd, Ste F   

                                          attributes             business_id  \
0                           {'GoodForKids': 'False'}  1SWheh84yJXfytovILXOAQ   
1  {'RestaurantsReservations': 'True', 'GoodForMe...  QXAEGFB4oINsVuTFxEYKFQ   
2  {'GoodForKids': 'True', 'NoiseLevel': 'u'avera...  gnKjwL_1w79qoiV3IC_xQQ   
3                                               None  xvX2CttrVhyG2z1dFg_0xw   
4  {'BusinessAcceptsBitcoin': 'False', 'ByAppoint...  HhyxOkGAM07SRYtlQ4wMFQ   

                                          categories         city  \
0                                  Golf, Active Life      Phoenix   
1  Specialty Food, Restaurants, Dim Sum, Imported...  Mississauga   
2                  Sushi Bars, Restaurants, Japanese    Charlotte   
3                      Insurance, Financial Services     Goodyear   
4  Plumbing, Shopping, Local Services, Home Servi...    Charlotte   

                                               hours  is_open   latitude  \
0                                               None        0  33.522143   
1  {'Monday': '9:0-0:0', 'Tuesday': '9:0-0:0', 'W...        1  43.605499   
2  {'Monday': '17:30-21:30', 'Wednesday': '17:30-...        1  35.092564   
3  {'Monday': '8:0-17:0', 'Tuesday': '8:0-17:0', ...        1  33.455613   
4  {'Monday': '7:0-23:0', 'Tuesday': '7:0-23:0', ...        1  35.190012   

    longitude                             name postal_code  review_count  \
0 -112.018481       Arizona Biltmore Golf Club       85016             5   
1  -79.652289       Emerald Chinese Restaurant     L5R 3E7           128   
2  -80.859132      Musashi Japanese Restaurant       28210           170   
3 -112.395596  Farmers Insurance - Paul Lorenz       85338             3   
4  -80.887223              Queen City Plumbing       28217             4   

   stars state  
0    3.0    AZ  
1    2.5    ON  
2    4.0    NC  
3    5.0    AZ  
4    4.0    NC

In [5]:
#df_user = pd.read_csv('data/user.csv', nrows = 100)

# df_review =  pd.read_csv('data/review.csv', usecols = ['business_id', 'user_id', 'stars'])
# user_cnts = df_review['user_id'].value_counts()
# top_users = user_cnts.loc[user_cnts>2].index
# df_review = df_review.loc[df_review['user_id'].isin(top_users)]
# df_review.to_csv('data/filtered_reviews.csv')

In [6]:
# reading filterdreview 

df_review = pd.read_csv('data/filtered_reviews.csv', index_col=0)

/Users/thomaslee/anaconda3/lib/python3.6/site-packages/numpy/lib/arraysetops.py:569: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)


In [7]:
# inumerating business_in and user_id with bid and uid 
def build_fmap_invmap(ser):
    uni_ele = ser.unique()
    fmap = {v:i for i, v in enumerate(uni_ele)}
    invmap = {i:v for i, v in enumerate(uni_ele)}
    return fmap, invmap

In [8]:
# setting debuging enviroment on (dbg =1) to turn it off (dbg = 0)
dbg = 1
if dbg:
    df_review = df_review.head(100000)

In [9]:
bus_fmap, bus_invmap = build_fmap_invmap(df_review['business_id'])
u_fmap, u_invmap = build_fmap_invmap(df_review['user_id'])

In [10]:
df_review['bid'] = df_review['business_id'].map(bus_fmap)

In [11]:
df_review['uid'] = df_review['user_id'].map(u_fmap)

In [12]:
df_review.head()

business_id  stars                 user_id  bid  uid
0  ujmEBvifdJM6h6RLv4wQIg    1.0  hG7b0MtEbXx5QzbzE6C_VA    0    0
2  WTqjgwHlXbSFevF32_DJVw    5.0  n6-Gk65cPZL6Uz8qRm3NYw    1    1
3  ikCg8xy5JIg_NGPx-MSIDA    5.0  dacAIZ6fTM6mqwW5uxkskg    2    2
6  3fw2X5bZYeW9xCz_zGhOHg    3.0  jlu4CztcSxrKx56ba1a5AQ    3    3
7  zvO-PJCpNk4fgAVUnExYAA    1.0  d6xvYpyzcfbF_AZ8vMB7QA    4    4

In [13]:
n_users, n_bus = df_review['uid'].nunique(), df_review['bid'].nunique()

In [14]:
n_dim = 5

In [15]:
# Initializing tensor flow at a randon number | n_users * n_dim (layers) initializing at some random number between
# -1 to 1 both for business and users. For internal layer. 
# PS > Create a function with code below: 

user_vector_raw = tf.Variable(tf.random_uniform([n_users, n_dim], minval = -1., maxval = 1.))
bus_vector_raw = tf.Variable(tf.random_uniform([n_bus, n_dim], minval = -1., maxval = 1.))

# running the tanh function to find 
user_vector = tf.tanh(user_vector_raw)
bus_vector = tf.tanh(bus_vector_raw)

# Stipulating the imput layer. 
users = tf.placeholder(tf.int32, shape=(None))
businesses = tf.placeholder(tf.int32, shape=(None))
ratings = tf.placeholder(tf.float32, shape=(None))

UserSampled = tf.nn.embedding_lookup(user_vector, users)
BusinessSampled = tf.nn.embedding_lookup(bus_vector, businesses)
UserSampled.set_shape([None, n_dim])
BusinessSampled.set_shape([None, n_dim])

# input tensors for products, users, ratings

Instructions for updating:
Colocations handled automatically by placer.


In [16]:
# Defining the output
# transfer into a fucntion
estimatedaffinitiesraw = tf.reduce_sum(UserSampled * BusinessSampled, 1)
estimatedaffinities = tf.sigmoid(estimatedaffinitiesraw)*5

In [17]:
# estimatedaffinities - ratings ask Lee to clarify ratings, where that ratings comes from? ask to explain the loss function 
# transfer into a function 
loss = tf.reduce_sum(tf.square(estimatedaffinities - ratings))
opt = tf.train.RMSPropOptimizer(learning_rate=.1).minimize(loss)

Instructions for updating:
Use tf.cast instead.


In [3]:
# Setting the session and intialize it 

sess = tf.Session()


In [19]:
# picking up 64 randon rows in order to run under memory capacity
rows = np.random.choice(df_review.shape[0], 64)

In [20]:
sess.run(tf.global_variables_initializer())

In [21]:
# Creating a loop to train under 64 random rows 
for i in range(10000):
    rows = np.random.choice(df_review.shape[0], 64)
    dfrows = df_review.iloc[rows]
    fd = {users:dfrows['uid'].values,
         businesses:dfrows['bid'].values,
         ratings:dfrows['stars'].values}
    _, l2loss = sess.run([opt, loss], fd)
    if i % 1000 == 0:
        print(l2loss)

234.92917
139.65031
127.449135
129.67441
137.12938
105.95755
72.79036
38.120255
50.260414
17.09154


In [22]:
user_values, bus_values = sess.run([user_vector, bus_vector])

In [23]:
bus_vec_df = pd.DataFrame(data = bus_values, index = 
                          [bus_invmap[i] for i in range(n_bus)])



In [24]:
bus_vec_df

0         1         2         3         4
ujmEBvifdJM6h6RLv4wQIg -0.999168  0.968609  0.999999 -0.999999 -0.999950
WTqjgwHlXbSFevF32_DJVw -0.999977  0.968243  0.902691 -0.999967 -0.999548
ikCg8xy5JIg_NGPx-MSIDA  0.971469 -0.992822 -0.997513 -0.999425 -0.978776
3fw2X5bZYeW9xCz_zGhOHg  0.323263 -0.985096 -0.228673  0.854754  0.924128
zvO-PJCpNk4fgAVUnExYAA  0.322046  0.908827 -0.860200  0.613535 -0.778720
b2jN2mm9Wf3RcrZCgfo1cg  0.999895  0.949014  0.999095 -0.999683 -0.999955
oxwGyA17NL6c5t1Etg5WgQ -1.000000 -0.380686 -0.512891  0.999999  0.231811
8mIrX_LrOnAqWsB5JrOojQ  0.999917  1.000000  0.999999  0.999981 -1.000000
FxLfqxdYPA6Z85PFKaqLrg  0.820339 -0.723934 -0.477904 -0.117361 -0.847304
AakkkTuGZA2KBodKi2_u8A  0.125206 -0.958670 -0.675109  0.721851 -0.472924
YvrylyuWgbP90RgMqZQVnQ -0.996443 -0.999989  0.999872  0.521035  0.999580
NyLYY8q1-H3hfsTwuwLPCg  0.999905 -0.999984  1.000000 -0.999988  0.999999
cHdJXLlKNWixBXpDwEGb_A -1.000000  0.078042  1.000000 -0.999998  0.999743
6lj2BJ4tJeu7db5asGHQ4w -0.983499 -0.989772  0.999954  0.999016  0.998888
y-Iw6dZflNix4BdwIyTNGA  0.999958  0.998425  0.999571  0.999808  0.098808
qx6WhZ42eDKmBchZDax4dQ -1.000000  0.999999 -1.000000 -1.000000  0.825428
Mem13A3C202RzT53npn4NA  0.999979  0.999963 -0.999995 -0.999995 -0.999994
I4Nr-MVc26qWr08-S3Q1ow  0.999997  0.998510 -0.778570  0.999999  0.999011
Sfc8Haz2Yri8Mo1L0E0TsA  0.944514 -0.408939 -0.991159 -0.999886 -0.828391
FQ1wBQb3aNeRMThSQEV0Qg  0.999887 -0.999981 -0.999957 -0.999973  0.999771
hd5xm20tfSa70-6UqD9-bg -0.999995  0.999989  0.999999 -0.999962 -0.995797
9nTF596jDvBBia2EXXiOOg  0.585845  0.372113  0.480732 -0.540376  0.999997
dm6sO_Y8JdKTE1ZM955yug -1.000000 -0.999996 -0.996845  0.999940 -0.999999
XTzKRvWciP_BZ9imk8mmPQ -0.999968  0.992252  0.999996  0.999981  0.999993
CDpoJiqgM04wqQTZ6QkTqQ -0.999608  0.999221  0.999974 -0.999992 -0.973785
3JxKzWquEbPC3yPIfoCiLw  0.987968 -0.999983 -0.999849  0.999997  0.999998
YSUcHqlKMPHHJ_cTrqtNrA -0.197734 -0.030216  0.980634  0.052246  0.637412
N0apJkxIem2E8irTBRKnHw -0.688197  0.999999  0.999997 -0.503577  0.997612
sMzNLdhJZGzYirIWt-fMAg  0.804915 -0.702456 -0.999553 -0.964167 -0.910029
IMLrj2klosTFvPRLv56cng -0.999759 -0.025185  0.190409  1.000000  0.999922
...                          ...       ...       ...       ...       ...
_WsGlZnbXBdPcs0qM2Qm7w  0.424676  0.410478 -0.353329 -0.367801 -0.554761
MGo5TXadUjDaPi5LYHArhA -0.589127 -0.196431 -0.102990 -0.487061  0.657215
um0brvgJQ_k0bfYQ4S6FpA  0.831234  0.876154 -0.116619  0.229859  0.537577
hJda5g5v_2rT3D-3mSf7cQ  0.473030 -0.313935 -0.266866  0.167385 -0.472284
0-7jRk54XXZgND3F3bo8sw -0.386405 -0.350356 -0.329616  0.110430  0.426619
aIVCYE8frb2ELMQkvqykrw -0.974878  0.997194 -0.979873  0.987116 -0.210115
lbYQ5INAEa1yCjS3XUFN_A -0.015523 -0.988150 -0.972276 -0.996493 -0.981709
m3Tatgcyw8dUzts0wqpKMg  0.991619  0.996743 -0.956701 -0.194522  0.990127
n2kOsDur7tCLygSa87glJQ -0.239214  0.479223 -0.054119 -0.278834 -0.387625
aiSFOdB2rMeA5cdwwmAGtA  0.122426  0.526987  0.576384  0.243287 -0.696179
lCcjph5wdCzGfTUO6LPocg -0.919939 -0.941600 -0.754893 -0.705624 -0.198996
Vt1iSx253f6yL0_TaSx6gQ -0.579798  0.037279  0.239419 -0.935097 -0.254323
VJTBDu7fc20u277sZckJzg -0.970536 -0.958020  0.987328  0.985134  0.988242
pBEM4bDE7MJ6G4SKmnjfbg  0.986973  0.996584 -0.993039  0.991935 -0.029115
3kvyAFaf_x9xRBjlKBaA-Q -0.858641  0.346764  0.324138  0.741606 -0.074790
JIlybDRCddKZAJ2-Y8SKCg  0.655537  0.880220  0.822958 -0.104807  0.676229
7uhvxvEu5x3t_OJk-zp2sQ  0.992988  0.086631 -0.943380  0.929691 -0.966021
bhosqo-Q1xp67iLqrd1Rbw -0.737891  0.490817  0.054776 -0.777474 -0.455678
0n3l_hKswZ3BJrRhSxOa1g -0.623080  0.280301 -0.560285  0.583856  0.474475
ZEuTAZjWKctjQLbQLCEP5Q  0.939045  0.997019 -0.978447 -0.996669  0.966949
HeH4qL9xS_XYnAQh6Yu8JQ  0.737115 -0.836914  0.454240 -0.495897  0.386484
U5zf1i_WzinhXLZH7X-N-Q -0.896284 -0.110262  0.594244  0.371042  0.867240
cEcTtJIc0h3rRuJWoTgcMg -0.107255  0.558121  0.320293 -0.164192  0.074243
_5S7EhbqW5_YoxuP

In [25]:
# Joining df_business + bus_vec_df
df_all = df_business.join(bus_vec_df, on='business_id', how='right')


In [26]:
# Dropping NaN columns 
df_all = df_all.dropna()

In [58]:
# Pulling user ID 4 and comparing to inverse map on uid (not sure why, maybe to check accuracy?)
uid = 4
u_invmap[uid]  

'd6xvYpyzcfbF_AZ8vMB7QA'

In [29]:
bname = 'cHdJXLlKNWixBXpDwEGb_A'
bid = bus_fmap[bname]

In [27]:
df_all.loc[df_all['categories'].str.contains('Restaurant') & 
           df_all['categories'].str.contains('Japanese')]

address  \
2                             10110 Johnston Rd, Ste 15   
73                                        436 Market St   
80                                   529-17th Avenue SW   
185                           2945 Lake Shore Boulevard   
343                                 10624 S Eastern Ave   
346                                       1909 E Ray Rd   
444                          3339 Boulevard des Sources   
507                           6989 N Hayden Rd, Ste A12   
524                               338-8338 18 Street SE   
577                                    1418 Rue Cartier   
706                  1716 W Horizon Ridge Pkwy, Ste 110   
766                                  599 Bloor Street W   
1037                            16 W Horizon Ridge Pkwy   
1057                      2035 Kennedy Road, 14th Floor   
1130                            1900 Cayuga St, Ste 101   
1236                               149 Rue Jean-Talon O   
1308                                  1137 17 Avenue SW   
1309                                  30 Bristol Road E   
1564                          7318 E Shea Blvd, Ste 101   
1637                          1061 W Pleasant Valley Rd   
1890                                       8750 Jane St   
1905                               2861 Dundas Street W   
1916                                572 Danforth Avenue   
1980                              1813 Rue Jean-Talon E   
1994                               7212 Macleod Trail S   
2043                     750 East Pyle Ave, Ste 108-109   
2078                                    3531 Forbes Ave   
2229                                 833 Bloor Street W   
2261                                      6025 Kruse Dr   
2347                 4355 W Spring Mountain Rd, Ste 107   
...                                                 ...   
15354                              1224 Dundas Street W   
15396                           360 Highway 7 E, Unit 3   
15715                 3820 Brentwood Road NW, Suite 130   
15832                                      8418 Park Rd   
16257                                      751 N Hwy 16   
16277                                 81 Harbord Street   
16345                                   4136 Library Rd   
16408                          2861 N Green Valley Pkwy   
16416                     3540 Rutherford Road, Unit 64   
16569                                     1276 W 6th St   
16826                                 1919 S Gilbert Rd   
17024                                 2036 Yonge Street   
17260                            5751 Boulevard Gouin O   
17286  Crystals Mall City Center, 3720 Las Vegas Blvd S   
17308                                    5904 Bryant St   
17461                       4206 E Chandler Blvd, Ste 7   
17750                        161 Frederick St, Unit 100   
17887                         1006 E Warner Rd, Ste 113   
17917                               6485 Mississauga Rd   
17924                              6705 Avenue Papineau   
17948                                   89 E Towne Mall   
17959                                80 Thickson Road S   
18195                              2795 Danforth Avenue   
18415                                      124 S 6th St   
18490                                    234 Euclid Ave   
18595                        15111 N Hayden Rd, Ste 120   
18748                                1232 Greene Avenue   
18863                       1616 Rue Sainte-Catherine O   
18991                                305 16th Avenue NW   
19016                             5795 W Bell Rd, Ste 1   

                                              attributes  \
2      {'GoodForKids': 'True', 'NoiseLevel': 'u'avera...   
73     {'OutdoorSeating': 'False', 'HasTV': 'True', '...   
80     {'WiFi': ''free'', 'GoodForDancing': 'False', ...   
185    {'RestaurantsDelivery': 'True', 'HasTV': 'True...   
343    {'RestaurantsTakeOut': 'True', 'NoiseLevel': '...   
346    {'RestaurantsDelivery'

### Testing (Passing train) 


In [30]:
bid

12

In [31]:
chipotle = bus_values[bid]

In [32]:
chipotle

array([-0.9999997 ,  0.07804164,  0.9999998 , -0.99999785,  0.99974287],
      dtype=float32)

In [33]:
japaneselover = user_values[uid]

In [34]:
bus_values

array([[-0.999168  ,  0.96860886,  0.9999986 , -0.9999991 , -0.9999496 ],
       [-0.9999766 ,  0.9682425 ,  0.9026906 , -0.99996734, -0.99954826],
       [ 0.9714687 , -0.992822  , -0.9975128 , -0.99942505, -0.97877586],
       ...,
       [-0.23577082,  0.65202653, -0.6258598 , -0.7044947 ,  0.3569681 ],
       [-0.99639076,  0.9810038 , -0.9945443 ,  0.9665813 , -0.9906568 ],
       [ 0.9697955 ,  0.28652716, -0.33573326,  0.08056628, -0.14556506]],
      dtype=float32)

In [35]:
np.square(bus_values - japaneselover[None,:]).sum(1).argsort()

array([ 1467,  2335, 10094, ...,  1979,   692,  3971])

In [36]:
np.square(bus_values - chipotle[None,:]).sum(1).argsort()

array([   12,  3771,  8903, ..., 10703,  2192,  4346])

In [37]:
def closest_businesses_to(business = None, user = None, df = None):
    if business is not None:
        target = bus_values[bus_fmap[business]]
    if user is not None:
        target = user_values[u_fmap[user]]
    if df is None:
        df = bus_values
    best_restaurants = np.square(df - target[None,:]).sum(1).argsort()
    return best_restaurants

In [38]:
midtown_japanese_restaurants = bus_values[:30,:]

In [39]:
closest_businesses_to(business = 'cHdJXLlKNWixBXpDwEGb_A')

array([   12,  3771,  8903, ..., 10703,  2192,  4346])

In [40]:
closest_businesses_to(user = 'ri7itn7-CdpsaPxTToK5cQ')

array([ 1467,  2335, 10094, ...,  1979,   692,  3971])

In [41]:
closest_businesses_to(user = 'ri7itn7-CdpsaPxTToK5cQ', df = midtown_japanese_restaurants)

array([26, 10, 12,  9,  6,  8, 13, 29,  3, 21,  1,  0, 24, 11, 20, 22, 27,
       28, 18,  2, 19, 15,  4, 23,  5, 25, 14, 16,  7, 17])